# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# Flutter项目代码分析配置
# 该配置提供严格的代码质量检查，确保代码符合Flutter最佳实践

analyzer:
  errors:
    prefer_expression_function_bodies: ignore
    flutter_style_todos: ignore
    use_setters_to_change_properties: ignore
    use_build_context_synchronously: ignore
  # 排除不需要分析的文件
  exclude:
    - "**/*.g.dart" # 生成的代码
    - "**/*.freezed.dart" # Freezed生成的代码
    - "build/**" # 构建文件
    - "ios/**" # iOS原生代码
    - "android/**" # Android原生代码
    - "windows/**" # Windows原生代码
    - "macos/**" # macOS原生代码
    - "linux/**" # Linux原生代码
    - "web/**" # Web文件

  # 强类型检查
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  # 开启实验性功能(已不再需要)
  # enable-experiment:
  #   - records
  #   - patterns

# Lint规则配置 - 严格模式，确保代码质量
linter:
  rules:
    # 基础规则
    prefer_single_quotes: true
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true

    # 文档和注释
    public_member_api_docs: false # 可以根据需要开启
    package_api_docs: false

    # 格式化
    lines_longer_than_80_chars: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true

    # 性能优化
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    prefer_collection_literals: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true

    # 空安全
    avoid_null_checks_in_equality_operators: true
    prefer_null_aware_operators: true

    # 安全性
    avoid_web_libraries_in_flutter: true
    no_duplicate_case_values: true

    # 样式和可读性
    curly_braces_in_flow_control_structures: true
    prefer_generic_function_type_aliases: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_typing_uninitialized_variables: true

    # 错误处理
    avoid_catching_errors: true
    avoid_returning_null_for_void: true

    # 测试相关
    avoid_relative_lib_imports: true
    # prefer_relative_imports: true  # 与always_use_package_imports冲突

    # 性能
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_spread_collections: true

    # 文件和包
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true

    # 其他重要规则
    always_declare_return_types: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cascade_invocations: true
    conditional_uri_does_not_exist: true
    deprecated_consistency: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: true
    hash_and_equals: true
    implementation_imports: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_logic_in_create_state: true
    no_runtimeType_toString: true
    null_closures: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    overridden_fields: true
    package_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_expression_function_bodies: true
    prefer_function_declarations_over_variables: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_not_operator: true
    prefer_mixin: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    recursive_getters: true
    require_trailing_commas: true
    secure_pubspec_urls: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_statements: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true
